'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/03Header'
// import AboutAnimation from './components/02AboutAnimation'
import Footer from './components/08Footer'
// import Head from 'next/head';
import Script from 'next/script'
import AmountContextProvider from './context/AmountContextProvider'
import LoginContextProvider from './context/LoginContextProvider'
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import Loading from './loading'
import { Suspense } from 'react'

// import NextNProgress from 'nextjs-progressbar';


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Pandit Misthan Bhandar',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <LoginContextProvider>
            <AmountContextProvider>
              <ToastContainer />
              <Header />
              {/* <AboutAnimation /> */}
              <Suspense fallback={<Loading />}>
                {children}
              </Suspense>
              <Footer />
            </AmountContextProvider>
          </LoginContextProvider>
        </body>
      </html>
      <Script src="https://checkout.razorpay.com/v1/checkout.js"
      />
    </>
  )
}
